### ISSUE TITLE
Can't type letter "s" on the search page in mobile layout

### ISSUE THREAD

**Issue by mtsknn** [ghivert/gloogle#11]
Can't type the letter "s" to the search field on the search page (https://gloogle.run/search?q= + anything) on Firefox on Mac with a narrow viewport (max 700px); the letter "s" doesn't appear. Additionally, on iOS Safari the virtual keyboard is closed.

The search field on the front page works.

Might be related to 73da6bc?

**Comment by ghivert** [comment]
Thanks for reporting!
The focus with `s` works by selecting the input by its ID. Of course, I duplicated the input in the mobile layout, and thus, the ID is duplicated on the page, which is illegal in HMTL. So this can lead to bad behaviour. I think here, no matter what you type, it tries to focus on the first hidden input, and it's not working. So it's preventing default.

There's a flag in the model, where `is_mobile` listen to media query. It would be good to completely remove the first input from the DOM on mobile, and only keep the second.
Another solution would be to not use ID, but classes, and find the first visible element.

If you feel motivated enough, you can PR. 😊

---

> Additionally, on iOS Safari the virtual keyboard is closed

Could you give more details on that one?

**Comment by mtsknn** [comment]
> If you feel motivated enough, you can PR. 😊

It seems I was more motivated to procrastinate. 🫣 😄

> > Additionally, on iOS Safari the virtual keyboard is closed
>
> Could you give more details on that one?

You already fixed this, but for the record: I meant that the iPhone's virtual keyboard slid away when trying to type an "s". Slid away like would happen when doing `input.blur()` (IIRC).
